# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

"""Convert a Markdown incident report to a professional PDF byte string.

Uses the ``markdown`` library to convert Markdown → HTML and WeasyPrint to
render HTML → PDF.  Both are pure-Python (WeasyPrint requires the system
``libpango`` and ``libpangocairo`` packages; see Dockerfile).
"""

from datetime import datetime, timezone
from typing import Optional

# ---------------------------------------------------------------------------
# HTML/CSS template for the generated PDF
# ---------------------------------------------------------------------------
_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <style>
    @page {{
      size: A4;
      margin: 2.5cm 2cm 2.5cm 2cm;
      @bottom-center {{
        content: "OFFICIAL – RESTRICTED  |  Page " counter(page) " of "
                 counter(pages);
        font-size: 8pt;
        color: #666;
        font-family: 'Liberation Sans', Arial, sans-serif;
      }}
    }}

    body {{
      font-family: 'Liberation Sans', Arial, sans-serif;
      font-size: 10.5pt;
      line-height: 1.6;
      color: #1a1a1a;
    }}

    /* ---- Header bar ---- */
    .report-header {{
      background: #1a3a5c;
      color: white;
      padding: 12pt 16pt;
      margin-bottom: 18pt;
    }}
    .report-header .org {{
      font-size: 9pt;
      opacity: 0.75;
      letter-spacing: 0.5pt;
      text-transform: uppercase;
    }}
    .report-header h1 {{
      font-size: 17pt;
      margin: 4pt 0 2pt 0;
      color: white;
      border: none;
    }}
    .report-header .meta {{
      font-size: 8.5pt;
      opacity: 0.85;
      margin-top: 2pt;
    }}

    /* ---- Headings ---- */
    h1 {{
      font-size: 16pt;
      color: #1a3a5c;
      border-bottom: 2px solid #1a3a5c;
      padding-bottom: 4pt;
      margin-top: 22pt;
      page-break-after: avoid;
    }}
    h2 {{
      font-size: 13pt;
      color: #1a3a5c;
      margin-top: 16pt;
      page-break-after: avoid;
    }}
    h3 {{
      font-size: 11.5pt;
      color: #333;
      margin-top: 12pt;
      page-break-after: avoid;
    }}

    /* ---- Tables ---- */
    table {{
      width: 100%;
      border-collapse: collapse;
      margin: 10pt 0 14pt 0;
      font-size: 9.5pt;
    }}
    th {{
      background: #1a3a5c;
      color: white;
      padding: 6pt 9pt;
      text-align: left;
      font-weight: bold;
    }}
    td {{
      padding: 5pt 9pt;
      border-bottom: 1px solid #dce3ec;
      vertical-align: top;
    }}
    tr:nth-child(even) td {{
      background: #f4f7fb;
    }}

    /* ---- Misc ---- */
    p   {{ margin: 5pt 0; }}
    ul, ol {{ margin: 5pt 0; padding-left: 18pt; }}
    li  {{ margin-bottom: 3pt; }}
    hr  {{ border: none; border-top: 1px solid #c0c8d4; margin: 14pt 0; }}
    strong {{ font-weight: bold; }}
    em {{ font-style: italic; }}
    code {{
      background: #f0f3f7;
      padding: 1pt 4pt;
      border-radius: 2pt;
      font-family: 'Liberation Mono', monospace;
      font-size: 9pt;
    }}

    /* ---- Footer note ---- */
    .report-footer {{
      margin-top: 28pt;
      border-top: 1px solid #c0c8d4;
      padding-top: 6pt;
      font-size: 8pt;
      color: #888;
      text-align: center;
    }}
  </style>
</head>
<body>

<div class="report-header">
  <div class="org">Smart City Public Safety Platform</div>
  <h1>Incident Report</h1>
  <div class="meta">
    Zone: <strong>{zone_id}</strong> &nbsp;|&nbsp;
    Generated: <strong>{generated_at}</strong> &nbsp;|&nbsp;
    Classification: <strong>OFFICIAL – RESTRICTED</strong>
  </div>
</div>

{body_html}

<div class="report-footer">
  This report was automatically generated by the Smart City AI Safety System.
  Treat as OFFICIAL – RESTRICTED.
</div>

</body>
</html>
"""


def markdown_to_pdf(
    markdown_text: str,
    zone_id: str = "unknown",
    generated_at: Optional[str] = None,
) -> bytes:
    """Render a Markdown incident report to PDF bytes.

    Args:
        markdown_text: Markdown source (the LLM-generated report body).
        zone_id: Zone identifier shown in the PDF header.
        generated_at: Human-readable timestamp for the PDF header.

    Returns:
        Raw PDF content as a byte string.

    Raises:
        ImportError: If ``markdown`` or ``weasyprint`` are not installed.
        Exception: Propagated from WeasyPrint on rendering failure.
    """
    import markdown  # pylint: disable=import-outside-toplevel
    from weasyprint import HTML  # pylint: disable=import-outside-toplevel

    ts = generated_at or datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    body_html = markdown.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "nl2br"],
    )

    full_html = _HTML_TEMPLATE.format(
        zone_id=zone_id,
        generated_at=ts,
        body_html=body_html,
    )

    return HTML(string=full_html).write_pdf()
